version: 2

models:
  - name: dim_customers
    description: One record per customer
    columns:
      - name: customer_id
        description: Primary key
        tests:
          - unique
          - not_null
      - name: first_order_date
        description: NULL when a customer has not yet placed an order.
      - name: lifetime_value
        description: non-negative total payment amount.

  - name: fct_orders
    description: One record per order
    columns:
      - name: order_id
        description: Primary key
        tests:
          - unique
          - not_null
      - name: amount
        description: amount of net payment of all orders.
        tests:
          - not_null
      - name: customer_id
        tests:
          - relationships:
              to: ref('stg_customers')
              field: customer_id

